services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8.0.25
    env_file: 
     - ./env/mysql.env
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
      - "127.0.0.1:3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" , "ping", "-P", "3306", "-proot"]
      interval: 10s
      timeout: 7s
      retries: 7
      start_period: 50s

  MyEcomm:
    container_name: myecomm-service
    hostname: myecomm-service
    env_file: 
      - ./env/mysql.env
      - ./env/myecomm.env
    build:
      context: .
      dockerfile: ./MyEcomm/Dockerfile
    image: my-ecomm:latest
    ports:
      - "1127.0.0.1:8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
